'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css";
import 'tailwindcss/tailwind.css'
import { Provider } from 'react-redux';
import { store } from "@/redux/store";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Nextjs ecommerce</title>
        <meta name='description' content='Description' />
      </head>
      <body className={inter.className}>

        <Provider store={store}>

          {children}

          <ToastContainer position='top-right' theme="colored"
            autoClose={2000} bodyClassName="toastBody"
          />
        </Provider>
      </body>
    </html>
  );
}
